### ISSUE TITLE
Pinned tabs should not be put into groups automatically

### ISSUE THREAD

**Issue by mafraqs** [loilo/auto-group-tabs#2]
Pinned tabs should be excluded from being automatically put into groups as they are pinned for a reason. 
Putting them into a group will remove them from being pinned.

**Comment by loilo** [comment]
Good catch. Going to take care of this. 👍

**Comment by loilo** [comment]
Good catch. Going to take care of this. 👍Am 22.03.2021 17:28 schrieb mafraqs ***@***.***>:
Pinned tabs should be excluded from being automatically put into groups as they are pinned for a reason.
Putting them into a group will remove them from being pinned.

**Comment by loilo** [comment]
This is going to be fixed in v0.0.3 which I just submitted for review, so this should be resolved in a couple days. I'll close this issue as soon as I see the review being finished.

@mafraqs Feel free to close this yourself when you realize the extension to be approved. Unfortunately, Google does not send me a notification, so I have to actively poll this.
