### ISSUE TITLE
How to work with file:/// format?

### ISSUE THREAD

**Issue by kerryj89** [loilo/auto-group-tabs#22]
I tried following the pattern in your app linked me to https://developer.chrome.com/docs/extensions/mv3/match_patterns/

Pattern (example) `file:///Users/somebody/dev/some-project` does not work.  I tried `dev/some-project` and `/Users/somebody/dev/some-project` also.  Any hints?  "Allow in Private" is set to enabled.  I noticed "Allow access to file URLs" is missing, but maybe not needed for your extension?

Thanks for the extension!

**Comment by loilo** [comment]
Hey @kerryj89,

that one's on me, sorry — I slightly messed up the input validation pattern for `file://` URLs.

Good news is that this bug is already fixed in the release I published on sunday (version 0.0.9). You just need to wait until someone from the Chrome team reviews the updated version and allows it into the Chrome web store. From my experience, this usually takes around 2-4 days, so you should receive the extension update by the end of the week. 🙂 

FYI: Since the bug has already been fixed in code, I'm going to close this issue.

**Comment by loilo** [comment]
There we go, the new version is out. You can manually upgrade by going to chrome://extensions/?id=danncghahncanipdoajmakdbeaophenb and press the "Update" button. 🙂
