### ISSUE TITLE
Tab sometimes doesn't get to the right tab group

### ISSUE THREAD

**Issue by yegle** [loilo/auto-group-tabs#23]
I'm still a bit fuzzy on how Chrome's tab groups works, but I've seen examples like this:

1. A tab in tab group foo is in focus.
2. I typed a new URL, which should be matched by a tab group bar by Auto Group Tabs

At this time 3 things might happen:
1. The tab move to the bar tab group (most of the time this is what happens).
2. The tab stays in foo tab group (after a while of randomly browsing, I would find a tab in a group not specified in Auto Group Tabs).
3. The tab furiously switch between foo tab group and bar tab group, causing Chrome to eat a lot of CPU. When this happens, I had to copy the URL, close the tab, then open a new tab and paste the URL.

2 and 3 are both very annoying. Is there a way to fix this? Or is this a bug in Chrome?

**Comment by loilo** [comment]
Hey @yegle, sorry for coming back to you so late about this.

I have seen parts of this problem problem before:
1. This has happened to me as well, but significantly less often in the last months.
2. That's not really a bug – it was just the behavior I implemented. I mostly use tab groups for organizing tabs belonging to different projects at work, so mostly any surfing I start from grouped tabs is still kind of related to the project and therefore should stay in that group as long as it does not match any other group configuration.

   However, by now there's a "strict" option for each tab group. If you enable it (when adding/editing the tab group), tabs will automatically be ungrouped if they no longer match the group.

   <img width="389" alt="" src="https://user-images.githubusercontent.com/1922624/186851009-67e147dd-5848-4ff6-93d3-3c630c16e651.png">


3. This sounds weird and has never happened to me. Do you use a lot of tab groups with just a color and no label? Because this mostly sounds like an erratic behavior of the extension when encountering conflicts (multiple tab groups with the same name + color combination).

In case you're still using the extension, do you still have these problems (in particular 1 and 3)?

**Comment by yegle** [comment]
Hi,

I think 1 would be WAI from my POV. It's good that there's a strict option now. I'd assume if I enable it I should always be seeing 1 but not 2.

Re 3, yes I do have two tab groups with the same name and two tab groups with the same color. I've changed both so they are all unique now. I'll keep watching for any reoccurring of 3.

Thank you for the strict option!

**Comment by loilo** [comment]
Hey @yegle, I'm going to close this issue as there seems to have been no recent misbehavior of the extension regarding your description. Feel free to post any additional information when the problem reoccurs and I'll re-open this issue. 🙂
