### ISSUE TITLE
When close the last tab in on group. Why to the plugin to remove the group not to close the tab.

### ISSUE THREAD

**Issue by huoxudong125** [loilo/auto-group-tabs#48]
![image](https://github.com/user-attachments/assets/1259ba10-4cdc-4563-8a77-3456ea31c4f4)

**Comment by loilo** [comment]
Hm. I don't get this alert in my Chrome. Anyway, this dialog comes from the browser itself, not from the extension, so I have no way to prevent this – sorry.

**Comment by huoxudong125** [comment]
It's a pity! but thanks for your reply.

**Comment by huoxudong125** [comment]
Does the design goal of the Chrome tab grouping strategy align with the objective of this extension? By observing Chrome, it seems to bundle web pages into a single tab for management, focusing on specific page combinations. However, the purpose of the extension is to combine rules rather than specific pages. Personally, I am more inclined towards grouping by rules rather than specific pages for management. Managing specific pages is more inclined towards tab bookmarking.

**Comment by loilo** [comment]
Not really sure what you're referring to with the "Chrome tab grouping strategy"?

**Comment by huoxudong125** [comment]
![image](https://github.com/user-attachments/assets/f9bf7cd4-8fbc-4a50-b7c9-46922a3c5ea7) 
![image](https://github.com/user-attachments/assets/c5ca220b-eeae-410a-8af5-7389a32397bf)

**Comment by huoxudong125** [comment]
Tab groups functionality is solely utilized for replaying the history of previously opened groups rather than incorporating new opened pages into the group. When the browser is closed, these pages are destroyed without recording. Upon reopening this webpage, the pages will only be placed in this tab group and will not be considered as needing to be placed in a new, similarly named tab group.

**Comment by loilo** [comment]
Okay, so what you're referring to specifically is Chrome's _saved_ tab groups. You're right, there's not a much of documentation about what that feature does.

From what I can tell, saved tab groups are exactly the same as regular tab groups: You create them manually, and you put tabs inside manually. There's no mechanism Chrome uses to insert tabs there automatically.

There seem to be three behavioral differences in saved tab groups:

1. Saved tab groups are synced across devices with the same Chrome profile (although those groups are not available on Android, due to Chrome on Android not having a tab groups feature at all).
2. Other than regular tab groups, saved tab groups can be hidden with the "Hide Group" option in its right-click menu. This is different from deleting them, since hidden tab groups can still be re-opened, either from the bookmark bar or from the main menu.
3. In the same sense, saved tab groups survive restarts of the browser. On browser startup (unless you configured your browser to always reopen the previous session), saved tab groups are essentially hidden as described in 2. and can be opened in the same ways.

So, Chrome's saved tab groups are mostly kind of a different way of creating bookmark folders.
